export const kittyWisdom = [
    "Let the sunbeam find your whiskers and your heart.",
    "Purr more, hiss less.",
    "Chase the groovy light, not the shadow.",
    "Every nap is a cosmic journey.",
    "Peace, love, and plenty of catnip.",
    "If you fit, you must sit—embrace your space.",
    "Meow to the universe, and the universe meows back.",
    "Let your paws dance on the rainbow road.",
    "The flower crown is always in style.",
    "Stretch like nobody’s watching.",
    "Find your sunspot and stay awhile.",
    "A purr a day keeps the bad vibes away.",
    "Groove to your own purr-chord.",
    "The best wisdom is found in a warm patch of sunlight.",
    "Let your tail be your compass.",
    "Peace begins with a gentle paw.",
    "Don’t stress, just press the snooze.",
    "Every box is a new adventure.",
    "Happiness is a sunbeam and a soft pillow.",
    "Be the cat you wish to see in the world.",
    "Let your whiskers tingle with curiosity.",
    "The universe is your scratching post.",
    "Love is a shared nap in a sunbeam.",
    "Follow the butterflies in your dreams.",
    "A little mischief is good for the soul.",
    "Peace, paws, and purrs to all.",
    "Let your heart bloom like catnip in spring.",
    "The grooviest cats wear their stripes with pride.",
    "Find your groove and ride it.",
    "Every meow is a mantra.",
    "Let your eyes see the magic in the mundane.",
    "The best journeys start with a curious nose.",
    "Be kind, rewind (your tail).",
    "Let your purrs ripple through the cosmos.",
    "A flower crown is lighter than a frown.",
    "Peace is a full belly and a warm lap.",
    "Let your soul nap under the stars.",
    "The world is your windowsill.",
    "Chase the sun, not the storm.",
    "Let your paws leave prints of love.",
    "Every whisker is a wish.",
    "The hippest cats share their catnip.",
    "Let your dreams be as wild as your fur.",
    "Peace signs and paw prints forever.",
    "The universe is best explored with a friend.",
    "Let your meow be your melody.",
    "A nap is the answer to most questions.",
    "Groove on, little lion.",
    "Let your heart purr in harmony with the world."
]